  - job_name: 'blackbox_tcp_connect'
    scrape_interval: 10s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
    - files: ['targets/blackbox_tcp_connect.yml']
      refresh_interval: 5s
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 10.55.5.25:9115
