groups:
- name: pod.rules
  rules:
  - alert: PodCpuuse
    expr: sum(rate(container_cpu_usage_seconds_total{image!=""}[1m])) by (pod, namespace) / (sum(container_spec_cpu_quota{image!=""}/100000) by (pod, namespace)) * 100 > 80
    for: 5m
    labels:
      severity: warn 
    annotations:
      summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }} CPU使用率过高"
      description: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }}  CPU使用率大于80%. (当前值:{{ $value }}%)"

  - alert: PodMemoryuse
    expr: sum(container_memory_rss{image!=""}) by(pod, namespace) / sum(container_spec_memory_limit_bytes{image!=""}) by(pod, namespace) * 100 != +inf > 80
    for: 5m
    labels:
      severity: warn 
    annotations:
      summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }} 内存使用率过高"
      description: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }}  内存使用率大于80%. (当前值:{{ $value }}%)"

  - alert: PodFailed
    expr: sum (kube_pod_status_phase{phase="Failed"}) by (pod,namespace) > 0
    for: 1m
    labels:
      severity: error 
    annotations:
      summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }} pod status is Failed"
      description: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }} pod status is Failed. (当前值:{{ $value }})"

  - alert: PodPending
    expr: sum (kube_pod_status_phase{phase="Pending"}) by (pod,namespace) > 0
    for: 1m
    labels:
      severity: error 
    annotations:
      summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }} pod status is Pending"
      description: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }} pod status is Pending. (当前值:{{ $value }})"

  - alert: PodNetworkReceive
    expr: sum (rate (container_network_receive_bytes_total{image!="",name=~"^k8s_.*"}[5m]) /1000) by (pod,namespace)  > 20000
    for: 5m
    labels:
      severity: warn
    annotations:
      summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }}  接受到的网络流量过大"
      description: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }}  接受到的网络流量大于20MB/s. (当前值:{{ $value }}B/s)"

  - alert: PodNetworkTransmit
    expr: sum (rate (container_network_transmit_bytes_total{image!="",name=~"^k8s_.*"}[5m]) /1000) by (pod,namespace) > 20000
    for: 5m
    labels:
      severity: warn 
    annotations:
      summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }}  传输的网络流量过大"
      description: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }}  传输的网络流量大于20MB/s. (当前值:{{ $value }}B/s)"

  - alert: PodRestart
    expr: sum (changes (kube_pod_container_status_restarts_total[1m])) by (pod,namespace) > 0
    for: 1m
    labels:
      severity: warn 
    annotations:
      summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }} pod is restart"
      description: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }}  在一分钟内重启. (当前值:{{ $value }})"
